#!/bin/sh

##
# Convert Rd files to latex and make them available for inclusion in 
# some other tex file (e.g. package manual)
# 
# Usage:  If you have an Rd file called "xxx.Rd" then in your manual use
# /include{xxx}
#
#
# 



#create the manual
pdflatex amelia
bibtex amelia
pdflatex amelia
pdflatex amelia
pdflatex amelia
pdflatex amelia

## report errors:
grep Warning amelia.log
grep "I'm skipping" amelia.blg
grep Warning amelia.blg
grep -i Error amelia.blg

## cleanup
rm -f *.aux *.toc *.log *.out *.blg *.bbl

